# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69cb91f73bc8f59238ca51d3cb22b197bc5e41765b2952702f965126a631ecac56d53cd46070e74095bfdbb484c4f99ed094c20e79ca11421cae81eb774d993

test:
  secret_key_base: 60c39a6d7bc106d676ed1123b40aa42de11d49ce64a19de437f77681bc8c777dc09987fc7ddb7e713f2cbc6af2c9de32c339118b65ca94bfbdaceccfac84e7dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
